import numpy as np
import math
from pathlib import Path
import numpy as np
import re

def generate_verilog_modules(
    H_FILE: str,
    COLORMAP_FILE: str,
    C_VAL: int,
    MODULE_FILE: str,
    READOUT_FILE: str,
    H_WIDTH: int = 5,
    TH_WIDTH: int = 16
) -> None:
    
    '''Generates solver.v and solver_readout.v based on the provided H matrix and colormap.
    Parameters:
    - H_FILE: Path to the CSV file containing the H matrix.
    - COLORMAP_FILE: Path to the text file containing the colormap.
    - C_VAL: The target SAT value for the problem instance.
    - MODULE_FILE: Path where the generated solver.v will be saved.
    - READOUT_FILE: Path where the generated solver_readout.v will be saved.
    - H_WIDTH: Bit-width for H matrix entries (default=5).
    - TH_WIDTH: Bit-width for threshold values (default=16).
    '''

    # Read H matrix and colormap
    H = np.loadtxt(H_FILE, delimiter=",", dtype=int)
    COLORMAP = np.loadtxt(COLORMAP_FILE, dtype=int) - 1
    NUM_CLS, NUM_VAR  = H.shape

    clause_defs       = [
        [(r, H[r, v]) for r in range(NUM_CLS) if H[r, v] != 0]
        for v in range(NUM_VAR)
    ]
    sigma_map         = [
        [v for v in range(NUM_VAR) if H[r, v] != 0]
        for r in range(NUM_CLS)
    ]
    col_sum_array     = [int(H[:, v].sum()) for v in range(NUM_VAR)]

    # Extract parameters
    MAX_COLOR         = int(COLORMAP.max() + 1)
    vars_per_color    = [list(np.where(COLORMAP == c)[0]) for c in range(MAX_COLOR)]
    col_nnz           = [(H[:, v] != 0).sum() for v in range(NUM_VAR)]
    MAX_COL_NNZ       = max(col_nnz)
    MAX_VAR_PER_COLOR = max(len(lst) for lst in vars_per_color)
    NOISE_CNT_WIDTH   = math.ceil(math.log2(MAX_VAR_PER_COLOR)) or 1

    # ------------------
    # GENERATE SOLVER.V
    # ------------------
    lines = []
    ap = lines.append

    ap("`timescale 1ns/1ps")
    ap("//-------------------------------------------------------------------------")
    ap(f"// {MODULE_FILE} - generated by generate_verilog_scripts.py")
    ap("//-------------------------------------------------------------------------")
    ap("module solver ")
    ap("(")
    ap("  input  wire                  clk, RESET, ENABLE, LOAD_T, LOAD_NOISE, RUN,")
    ap("  input  wire                  T_IN,")
    ap(f"  input  wire signed [{TH_WIDTH-1}:0]   NOISE_IN,")
    ap(f"  output reg  [{NUM_CLS-1}:0]    T_reg")
    ap(");")
    ap("")

    ap(f"  localparam integer NUM_CLS           = {NUM_CLS};")
    ap(f"  localparam integer NUM_VAR           = {NUM_VAR};")
    ap(f"  localparam integer MAX_COLOR         = {MAX_COLOR};")
    ap(f"  localparam integer MAX_COL_NNZ       = {MAX_COL_NNZ};")
    ap(f"  localparam integer MAX_VAR_PER_COLOR = {MAX_VAR_PER_COLOR};")
    ap(f"  localparam integer H_WIDTH           = {H_WIDTH};")
    ap(f"  localparam integer TH_WIDTH          = {TH_WIDTH};")
    ap(f"  integer i, i_cls;")
    ap(f"  reg [$clog2(NUM_CLS)-1:0]               t_load_count;")
    ap(f"  reg [{NOISE_CNT_WIDTH-1}:0]             noise_load_count;")
    ap(f"  reg [$clog2(MAX_COLOR)-1:0]     current_color, next_color;")
    ap("  reg [NUM_CLS-1:0]            T_next;")
    ap(f"  reg [TH_WIDTH-1:0]           noisethld_vec [0:MAX_VAR_PER_COLOR-1];")
    ap("  reg update;")
    ap("")

    ap("  always @(posedge clk or posedge RESET) begin")
    ap("    if (RESET) begin")
    ap("      T_reg            <= {NUM_CLS{1'b0}};")
    ap("      t_load_count     <= {($clog2(NUM_CLS)){1'b0}};")
    ap("      noise_load_count <= {"+str(NOISE_CNT_WIDTH)+"{1'b0}};")
    ap("      current_color    <= {($clog2(MAX_COLOR)){1'b0}};")
    ap("      update <= 1'b0;")
    ap("      for (i = 0; i < MAX_VAR_PER_COLOR; i = i + 1)")
    ap("        noisethld_vec[i] <= {TH_WIDTH{1'b0}};")
    ap("    end else if (ENABLE) begin")
    ap("      if (LOAD_T) begin")
    ap("        T_reg[t_load_count] <= T_IN;")
    ap("        t_load_count       <= t_load_count + 1;")
    ap("      end else if (LOAD_NOISE) begin")
    ap("        noisethld_vec[noise_load_count] <= NOISE_IN;")
    ap("        noise_load_count               <= noise_load_count + 1;")
    ap("      end else if (RUN) begin")
    ap("        update <= 1'b1;")
    ap("        current_color <= next_color;")
    ap("        // shift thresholds and inject new")
    ap("")
    ap("        for (i = MAX_VAR_PER_COLOR-1; i > 0; i = i-1)")
    ap("            noisethld_vec[i] <= noisethld_vec[i-1];")
    ap("        noisethld_vec[0] <= NOISE_IN;")
    ap("        T_reg         <= T_next;")
    ap("      end")
    ap("    end")
    ap("  end")
    ap("")

    for v, entries in enumerate(clause_defs):
        terms = []
        for r, val in entries:
            lit = f"-{H_WIDTH}'sd{abs(val)}" if val < 0 else f"{H_WIDTH}'sd{val}"
            terms.append(f"(T_reg[{r}] ? {lit} : {H_WIDTH}'sd0)")
        pad = [f"{{H_WIDTH{{1'b0}}}}"] * (MAX_COL_NNZ - len(terms))
        all_terms = terms + pad
        ap(f"  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_{v} = " +
        "{" + ", ".join(all_terms) + "};")
    ap("")

    ap(f"  reg signed [H_WIDTH*MAX_COL_NNZ-1:0] q_add_in [0:MAX_VAR_PER_COLOR-1];")
    ap("  always @* begin")
    ap("    case (current_color)")
    for c, vars_ in enumerate(vars_per_color):
        assigns = " ".join(f"q_add_in[{i}] = q_pp_flat_{vars_[i]};"
                        for i in range(len(vars_)))
        zero_pad = " ".join(f"q_add_in[{i}] = {{H_WIDTH*MAX_COL_NNZ{{1'b0}}}};"
                            for i in range(len(vars_), MAX_VAR_PER_COLOR))
        ap(f"      {c}: begin {assigns} {zero_pad} end")
    ap("      default: begin")
    for i in range(MAX_VAR_PER_COLOR):
        ap(f"        q_add_in[{i}] = {{H_WIDTH*MAX_COL_NNZ{{1'b0}}}};")
    ap("      end")
    ap("    endcase")
    ap("  end")
    ap("")

    ap(f"  wire signed [TH_WIDTH-1:0] q_cal [0:MAX_VAR_PER_COLOR-1];")
    for i in range(MAX_VAR_PER_COLOR):
        ap("  adder_tree #("
        ".IN_WIDTH(H_WIDTH), "
        ".N_INPUTS(MAX_COL_NNZ), "
        ".OUT_WIDTH(TH_WIDTH)) "
        f"u_at_{i} ("
        f".in_terms_flat(q_add_in[{i}]), "
        f".sum_out(q_cal[{i}]));")
    ap("")

    ap(f"  reg [TH_WIDTH-1:0] noisethld_adj [0:MAX_VAR_PER_COLOR-1];")
    ap("  integer j;")
    ap("  always @* begin")
    ap("    for (j = 0; j < MAX_VAR_PER_COLOR; j = j + 1)")
    ap("      noisethld_adj[j] = {TH_WIDTH{1'b0}};")
    ap("    case (current_color)")
    for c, vars_ in enumerate(vars_per_color):
        ap(f"      {c}: begin")
        for i, v in enumerate(vars_):
            half = int(col_sum_array[v] * 1)
            ap(f"        noisethld_adj[{i}] = noisethld_vec[{i}] + {half};")
        ap("      end")
    ap("      default: ;")
    ap("    endcase")
    ap("  end")
    ap("")

    ap("  wire q_color [0:MAX_VAR_PER_COLOR-1];")
    ap("  genvar gi;")
    ap("  generate for (gi = 0; gi < MAX_VAR_PER_COLOR; gi = gi + 1) begin")
    ap("      assign q_color[gi] = ((q_cal[gi]<<<1) < $signed(noisethld_adj[gi]));")
    ap("    end endgenerate")
    ap("")

    ap("  reg [NUM_VAR-1:0] q_vector_r;")
    ap("  always @* begin")
    ap("    q_vector_r = {NUM_VAR{1'b0}};")
    ap("    case (current_color)")
    for c, vars_ in enumerate(vars_per_color):
        assigns = " ".join(f"q_vector_r[{v}] = q_color[{i}];"
                        for i, v in enumerate(vars_))
        ap(f"      {c}: begin {assigns} end")
    ap("      default: q_vector_r = {NUM_VAR{1'b0}};")
    ap("    endcase")
    ap("  end")
    ap("  wire [NUM_VAR-1:0] q_vector = q_vector_r;")
    ap("")

    ap("  wire [NUM_CLS-1:0] sigma;")
    for r, vs in enumerate(sigma_map):
        expr = " ^ ".join(f"q_vector[{v}]" for v in vs) or "1'b0"
        ap(f"  assign sigma[{r}] = {expr};")
    ap("")

    ap("  always @* begin")
    ap("    for (i_cls = 0; i_cls < NUM_CLS; i_cls = i_cls + 1) begin")
    ap("      T_next[i_cls] = (update) ? (sigma[i_cls] ^ T_reg[i_cls])")
    ap("                              : T_reg[i_cls];")
    ap("    end")
    ap("    next_color = (update) ? ((current_color == MAX_COLOR-1) ? 0 : (current_color + 1)) : 0;")
    ap("  end")
    ap("endmodule")
    ap("")

    with open(MODULE_FILE, 'w') as f:
        f.write("\n".join(lines))

    print(F"Generated {MODULE_FILE}")

    # ---------------------------
    # GENERATE SOLVER_READOUT.V
    # ---------------------------

    row_vals = []
    for r in range(NUM_CLS):
        nz = H[r, :]
        vals = nz[nz != 0]
        v = int(vals[0]) if len(vals) else 0
        row_vals.append(v)

    lines = []
    ap = lines.append

    ap("`timescale 1ns/1ps")
    ap("//-------------------------------------------------------------------------")
    ap(f"// {READOUT_FILE} - generated by generate_verilog_scripts.py")
    ap("//-------------------------------------------------------------------------")
    ap("module solver_readout (")
    ap("  input  wire                  clk,")
    ap("  input  wire                  RESET,")
    ap("  input  wire                  ENABLE,")
    ap("  input  wire                  LOAD_T,")
    ap("  input  wire                  LOAD_NOISE,")
    ap("  input  wire                  RUN,")
    ap("  input  wire                  READ,")
    ap(f"  input  wire signed [{TH_WIDTH-1}:0]    NOISE_IN,")
    ap("  input  wire                  T_IN,")
    ap("  output wire                  SOLVED,")
    ap("  output reg                   T_READOUT,")
    ap(f"  output wire signed [{TH_WIDTH-1}:0]    sat_out")
    ap(");")
    ap("")

    ap(f"  localparam integer NUM_CLS   = {NUM_CLS};")
    ap(f"  localparam integer C         = {C_VAL};")
    ap(f"  localparam integer H_WIDTH   = {H_WIDTH};")
    ap(f"  localparam integer TH_WIDTH  = {TH_WIDTH};")
    ap("")
    ap("  wire [NUM_CLS-1:0]               T_reg;")
    ap("")
    ap(f"  wire signed [H_WIDTH + $clog2(NUM_CLS)-1:0] sum_terms = (")

    for k in range(NUM_CLS-1, -1, -1):
        v = row_vals[k]
        sign_lit = f"{H_WIDTH}'sd{abs(v)}"
        if v < 0:
            lit = f"( T_reg[{k}] ? -{sign_lit} :  {sign_lit})"
        else:
            lit = f"( T_reg[{k}] ?  {sign_lit} : -{sign_lit})"
        # comma = "" if k > 0 else ";"
        plus = "+" if k != NUM_CLS-1 else " "
        ap(f"    {plus}{lit}  // {k}")
    ap("  );")
    ap("")

    ap(f"  wire signed [TH_WIDTH+{NUM_CLS.bit_length()}:0] acc_full = $signed(7 * C) + sum_terms;")
    ap("  assign sat_out = $signed(acc_full) >>> 3;")
    ap("  assign SOLVED  = (sat_out == $signed(C));")
    ap("")

    read_bits = math.ceil(math.log2(NUM_CLS+2)) if NUM_CLS > 1 else 1

    ap("  reg                   read_active;")
    ap("  reg                   read_active_d;")
    ap(f"  reg [{read_bits-1}:0] read_count;")

    ap(f"  always @(posedge clk or posedge RESET) begin")
    ap(f"    if (RESET) begin")
    ap("      read_active   <= 1'b0;")
    ap("      read_active_d <= 1'b0;")
    ap(f"      read_count    <= {read_bits}'d0;")
    ap(f"      T_READOUT     <= 1'b0;")
    ap("    end else if (ENABLE) begin")
    ap("      read_active_d <= READ;")
    ap("      // start read on rising edge of READ")
    ap("      if (READ & ~read_active_d)")
    ap("        read_active <= 1'b1;")
    ap("      // stop when READ deasserts or after NUM_CLS bits")
    ap("      else if (~READ || (read_count == NUM_CLS-1))")
    ap("        read_active <= 1'b0;")
    ap("")
    ap("      if (read_active) begin")
    ap(f"        T_READOUT <= T_reg[read_count];")
    ap("        // increment but don\'t overflow")
    ap(f"        if (read_count < NUM_CLS-1)")
    ap("          read_count <= read_count + 1;")
    ap("      end else begin")
    ap(f"        read_count <= {read_bits}'d0;")
    ap("      end")
    ap("    end")
    ap("  end")

    ap("  wire ENABLE_INTERNAL = ENABLE && ~READ;")
    ap("  solver u_solver (")
    ap("    .clk        (clk),")
    ap("    .RESET      (RESET),")
    ap("    .ENABLE     (ENABLE_INTERNAL),")
    ap("    .LOAD_T     (LOAD_T),")
    ap("    .LOAD_NOISE (LOAD_NOISE),")
    ap("    .RUN        (RUN),")
    ap("    .T_IN       (T_IN),")
    ap("    .NOISE_IN   (NOISE_IN),")
    ap("    .T_reg      (T_reg)")
    ap("  );")
    ap("")
    ap("endmodule")

    with open(READOUT_FILE, 'w') as f:
        f.write("\n".join(lines))

    print(f"Generated {READOUT_FILE}")

def main():
    '''Main function to iterate over H-matrix files and generate corresponding Verilog modules.'''

    # ---------------------- TWEAK THESE ----------------------
    input_base = Path("./H_matrices")
    cmap_base = Path("./Colormaps")
    verilog_dir = Path("./Verilog_files")
    verilog_dir.mkdir(parents=True, exist_ok=True)

    # Mapping from problem size to C_VAL
    cval_map = {
        '20': 91,
        '100': 430,
        '175': 753,
        '250': 1065
    }

    # Iterate over each H-matrix directory
    for h_dir in sorted(input_base.iterdir()):
        if not h_dir.is_dir():
            continue
        for h_csv in sorted(h_dir.glob("*.csv")):
            stem = h_csv.stem.replace("H_matrix_", "")
            m = re.search(r"(\d+)", stem)
            if not m:
                print(f"Cannot determine size for {stem}, skipping.")
                continue
            size = m.group(1)
            if size not in cval_map:
                print(f"Size {size} not in cval_map for {stem}, skipping.")
                continue
            c_val = cval_map[size]

            cmap_file = cmap_base / f"colormap_{stem}.txt"
            if not cmap_file.exists():
                raise FileNotFoundError(f"Expected colormap file {cmap_file}")

            module_file  = verilog_dir / "solver_modules" / f"{stem}" / f"solver_{stem}.v"
            readout_file = verilog_dir / "solver_modules" / f"{stem}" / f"solver_readout_{stem}.v"
            module_file.parent.mkdir(parents=True, exist_ok=True)
            readout_file.parent.mkdir(parents=True, exist_ok=True)

            print(f"Generating Verilog for {stem}...")
            generate_verilog_modules(
                H_FILE        = str(h_csv),
                COLORMAP_FILE = str(cmap_file),
                C_VAL         = c_val,
                MODULE_FILE   = str(module_file),
                READOUT_FILE  = str(readout_file)
            )

if __name__ == "__main__":
    main()
