`timescale 1ns/1ps
//-------------------------------------------------------------------------
// Verilog_files\solver_modules\uf20_03\solver_readout_uf20_03.v - generated by generate_verilog_scripts.py
//-------------------------------------------------------------------------
module solver_readout (
  input  wire                  clk,
  input  wire                  RESET,
  input  wire                  ENABLE,
  input  wire                  LOAD_T,
  input  wire                  LOAD_NOISE,
  input  wire                  RUN,
  input  wire                  READ,
  input  wire signed [15:0]    NOISE_IN,
  input  wire                  T_IN,
  output wire                  SOLVED,
  output reg                   T_READOUT,
  output wire signed [15:0]    sat_out
);

  localparam integer NUM_CLS   = 224;
  localparam integer C         = 91;
  localparam integer H_WIDTH   = 5;
  localparam integer TH_WIDTH  = 16;

  wire [NUM_CLS-1:0]               T_reg;

  wire signed [H_WIDTH + $clog2(NUM_CLS)-1:0] sum_terms = (
     ( T_reg[223] ?  5'sd2 : -5'sd2)  // 223
    +( T_reg[222] ?  5'sd1 : -5'sd1)  // 222
    +( T_reg[221] ? -5'sd5 :  5'sd5)  // 221
    +( T_reg[220] ?  5'sd2 : -5'sd2)  // 220
    +( T_reg[219] ? -5'sd1 :  5'sd1)  // 219
    +( T_reg[218] ? -5'sd3 :  5'sd3)  // 218
    +( T_reg[217] ?  5'sd3 : -5'sd3)  // 217
    +( T_reg[216] ?  5'sd1 : -5'sd1)  // 216
    +( T_reg[215] ? -5'sd2 :  5'sd2)  // 215
    +( T_reg[214] ?  5'sd2 : -5'sd2)  // 214
    +( T_reg[213] ?  5'sd3 : -5'sd3)  // 213
    +( T_reg[212] ? -5'sd1 :  5'sd1)  // 212
    +( T_reg[211] ? -5'sd1 :  5'sd1)  // 211
    +( T_reg[210] ? -5'sd1 :  5'sd1)  // 210
    +( T_reg[209] ?  5'sd1 : -5'sd1)  // 209
    +( T_reg[208] ? -5'sd1 :  5'sd1)  // 208
    +( T_reg[207] ?  5'sd1 : -5'sd1)  // 207
    +( T_reg[206] ?  5'sd1 : -5'sd1)  // 206
    +( T_reg[205] ? -5'sd1 :  5'sd1)  // 205
    +( T_reg[204] ?  5'sd1 : -5'sd1)  // 204
    +( T_reg[203] ?  5'sd1 : -5'sd1)  // 203
    +( T_reg[202] ? -5'sd5 :  5'sd5)  // 202
    +( T_reg[201] ? -5'sd1 :  5'sd1)  // 201
    +( T_reg[200] ?  5'sd2 : -5'sd2)  // 200
    +( T_reg[199] ?  5'sd1 : -5'sd1)  // 199
    +( T_reg[198] ? -5'sd1 :  5'sd1)  // 198
    +( T_reg[197] ? -5'sd2 :  5'sd2)  // 197
    +( T_reg[196] ?  5'sd1 : -5'sd1)  // 196
    +( T_reg[195] ?  5'sd1 : -5'sd1)  // 195
    +( T_reg[194] ? -5'sd1 :  5'sd1)  // 194
    +( T_reg[193] ? -5'sd3 :  5'sd3)  // 193
    +( T_reg[192] ? -5'sd1 :  5'sd1)  // 192
    +( T_reg[191] ? -5'sd2 :  5'sd2)  // 191
    +( T_reg[190] ?  5'sd1 : -5'sd1)  // 190
    +( T_reg[189] ? -5'sd4 :  5'sd4)  // 189
    +( T_reg[188] ? -5'sd1 :  5'sd1)  // 188
    +( T_reg[187] ? -5'sd1 :  5'sd1)  // 187
    +( T_reg[186] ?  5'sd1 : -5'sd1)  // 186
    +( T_reg[185] ?  5'sd2 : -5'sd2)  // 185
    +( T_reg[184] ? -5'sd1 :  5'sd1)  // 184
    +( T_reg[183] ? -5'sd1 :  5'sd1)  // 183
    +( T_reg[182] ? -5'sd2 :  5'sd2)  // 182
    +( T_reg[181] ?  5'sd1 : -5'sd1)  // 181
    +( T_reg[180] ?  5'sd1 : -5'sd1)  // 180
    +( T_reg[179] ? -5'sd2 :  5'sd2)  // 179
    +( T_reg[178] ? -5'sd3 :  5'sd3)  // 178
    +( T_reg[177] ? -5'sd1 :  5'sd1)  // 177
    +( T_reg[176] ? -5'sd1 :  5'sd1)  // 176
    +( T_reg[175] ? -5'sd1 :  5'sd1)  // 175
    +( T_reg[174] ? -5'sd1 :  5'sd1)  // 174
    +( T_reg[173] ?  5'sd1 : -5'sd1)  // 173
    +( T_reg[172] ?  5'sd1 : -5'sd1)  // 172
    +( T_reg[171] ?  5'sd1 : -5'sd1)  // 171
    +( T_reg[170] ?  5'sd1 : -5'sd1)  // 170
    +( T_reg[169] ?  5'sd2 : -5'sd2)  // 169
    +( T_reg[168] ?  5'sd1 : -5'sd1)  // 168
    +( T_reg[167] ? -5'sd1 :  5'sd1)  // 167
    +( T_reg[166] ?  5'sd9 : -5'sd9)  // 166
    +( T_reg[165] ? -5'sd1 :  5'sd1)  // 165
    +( T_reg[164] ?  5'sd1 : -5'sd1)  // 164
    +( T_reg[163] ? -5'sd1 :  5'sd1)  // 163
    +( T_reg[162] ? -5'sd1 :  5'sd1)  // 162
    +( T_reg[161] ?  5'sd1 : -5'sd1)  // 161
    +( T_reg[160] ? -5'sd1 :  5'sd1)  // 160
    +( T_reg[159] ? -5'sd1 :  5'sd1)  // 159
    +( T_reg[158] ? -5'sd1 :  5'sd1)  // 158
    +( T_reg[157] ?  5'sd2 : -5'sd2)  // 157
    +( T_reg[156] ?  5'sd1 : -5'sd1)  // 156
    +( T_reg[155] ? -5'sd1 :  5'sd1)  // 155
    +( T_reg[154] ?  5'sd2 : -5'sd2)  // 154
    +( T_reg[153] ?  5'sd1 : -5'sd1)  // 153
    +( T_reg[152] ?  5'sd8 : -5'sd8)  // 152
    +( T_reg[151] ?  5'sd1 : -5'sd1)  // 151
    +( T_reg[150] ? -5'sd1 :  5'sd1)  // 150
    +( T_reg[149] ?  5'sd1 : -5'sd1)  // 149
    +( T_reg[148] ?  5'sd1 : -5'sd1)  // 148
    +( T_reg[147] ? -5'sd1 :  5'sd1)  // 147
    +( T_reg[146] ? -5'sd1 :  5'sd1)  // 146
    +( T_reg[145] ?  5'sd1 : -5'sd1)  // 145
    +( T_reg[144] ? -5'sd2 :  5'sd2)  // 144
    +( T_reg[143] ?  5'sd1 : -5'sd1)  // 143
    +( T_reg[142] ? -5'sd1 :  5'sd1)  // 142
    +( T_reg[141] ?  5'sd2 : -5'sd2)  // 141
    +( T_reg[140] ? -5'sd1 :  5'sd1)  // 140
    +( T_reg[139] ? -5'sd1 :  5'sd1)  // 139
    +( T_reg[138] ? -5'sd1 :  5'sd1)  // 138
    +( T_reg[137] ?  5'sd1 : -5'sd1)  // 137
    +( T_reg[136] ?  5'sd4 : -5'sd4)  // 136
    +( T_reg[135] ?  5'sd1 : -5'sd1)  // 135
    +( T_reg[134] ? -5'sd1 :  5'sd1)  // 134
    +( T_reg[133] ?  5'sd1 : -5'sd1)  // 133
    +( T_reg[132] ? -5'sd2 :  5'sd2)  // 132
    +( T_reg[131] ? -5'sd1 :  5'sd1)  // 131
    +( T_reg[130] ?  5'sd1 : -5'sd1)  // 130
    +( T_reg[129] ? -5'sd1 :  5'sd1)  // 129
    +( T_reg[128] ? -5'sd1 :  5'sd1)  // 128
    +( T_reg[127] ?  5'sd2 : -5'sd2)  // 127
    +( T_reg[126] ?  5'sd1 : -5'sd1)  // 126
    +( T_reg[125] ?  5'sd2 : -5'sd2)  // 125
    +( T_reg[124] ?  5'sd1 : -5'sd1)  // 124
    +( T_reg[123] ?  5'sd1 : -5'sd1)  // 123
    +( T_reg[122] ?  5'sd1 : -5'sd1)  // 122
    +( T_reg[121] ? -5'sd1 :  5'sd1)  // 121
    +( T_reg[120] ? -5'sd1 :  5'sd1)  // 120
    +( T_reg[119] ?  5'sd1 : -5'sd1)  // 119
    +( T_reg[118] ? -5'sd2 :  5'sd2)  // 118
    +( T_reg[117] ?  5'sd2 : -5'sd2)  // 117
    +( T_reg[116] ?  5'sd1 : -5'sd1)  // 116
    +( T_reg[115] ?  5'sd2 : -5'sd2)  // 115
    +( T_reg[114] ?  5'sd1 : -5'sd1)  // 114
    +( T_reg[113] ?  5'sd3 : -5'sd3)  // 113
    +( T_reg[112] ? -5'sd1 :  5'sd1)  // 112
    +( T_reg[111] ? -5'sd1 :  5'sd1)  // 111
    +( T_reg[110] ? -5'sd1 :  5'sd1)  // 110
    +( T_reg[109] ?  5'sd1 : -5'sd1)  // 109
    +( T_reg[108] ? -5'sd1 :  5'sd1)  // 108
    +( T_reg[107] ?  5'sd2 : -5'sd2)  // 107
    +( T_reg[106] ? -5'sd1 :  5'sd1)  // 106
    +( T_reg[105] ?  5'sd2 : -5'sd2)  // 105
    +( T_reg[104] ? -5'sd1 :  5'sd1)  // 104
    +( T_reg[103] ? -5'sd1 :  5'sd1)  // 103
    +( T_reg[102] ? -5'sd2 :  5'sd2)  // 102
    +( T_reg[101] ? -5'sd1 :  5'sd1)  // 101
    +( T_reg[100] ?  5'sd1 : -5'sd1)  // 100
    +( T_reg[99] ?  5'sd2 : -5'sd2)  // 99
    +( T_reg[98] ? -5'sd2 :  5'sd2)  // 98
    +( T_reg[97] ? -5'sd1 :  5'sd1)  // 97
    +( T_reg[96] ?  5'sd2 : -5'sd2)  // 96
    +( T_reg[95] ?  5'sd1 : -5'sd1)  // 95
    +( T_reg[94] ?  5'sd1 : -5'sd1)  // 94
    +( T_reg[93] ?  5'sd1 : -5'sd1)  // 93
    +( T_reg[92] ? -5'sd1 :  5'sd1)  // 92
    +( T_reg[91] ?  5'sd1 : -5'sd1)  // 91
    +( T_reg[90] ? -5'sd1 :  5'sd1)  // 90
    +( T_reg[89] ? -5'sd2 :  5'sd2)  // 89
    +( T_reg[88] ? -5'sd1 :  5'sd1)  // 88
    +( T_reg[87] ?  5'sd1 : -5'sd1)  // 87
    +( T_reg[86] ?  5'sd1 : -5'sd1)  // 86
    +( T_reg[85] ? -5'sd1 :  5'sd1)  // 85
    +( T_reg[84] ?  5'sd1 : -5'sd1)  // 84
    +( T_reg[83] ?  5'sd2 : -5'sd2)  // 83
    +( T_reg[82] ?  5'sd2 : -5'sd2)  // 82
    +( T_reg[81] ?  5'sd3 : -5'sd3)  // 81
    +( T_reg[80] ? -5'sd1 :  5'sd1)  // 80
    +( T_reg[79] ?  5'sd1 : -5'sd1)  // 79
    +( T_reg[78] ?  5'sd2 : -5'sd2)  // 78
    +( T_reg[77] ? -5'sd1 :  5'sd1)  // 77
    +( T_reg[76] ? -5'sd1 :  5'sd1)  // 76
    +( T_reg[75] ?  5'sd2 : -5'sd2)  // 75
    +( T_reg[74] ? -5'sd1 :  5'sd1)  // 74
    +( T_reg[73] ? -5'sd1 :  5'sd1)  // 73
    +( T_reg[72] ? -5'sd1 :  5'sd1)  // 72
    +( T_reg[71] ? -5'sd1 :  5'sd1)  // 71
    +( T_reg[70] ? -5'sd1 :  5'sd1)  // 70
    +( T_reg[69] ?  5'sd1 : -5'sd1)  // 69
    +( T_reg[68] ? -5'sd1 :  5'sd1)  // 68
    +( T_reg[67] ? -5'sd1 :  5'sd1)  // 67
    +( T_reg[66] ?  5'sd1 : -5'sd1)  // 66
    +( T_reg[65] ?  5'sd3 : -5'sd3)  // 65
    +( T_reg[64] ?  5'sd1 : -5'sd1)  // 64
    +( T_reg[63] ?  5'sd1 : -5'sd1)  // 63
    +( T_reg[62] ?  5'sd1 : -5'sd1)  // 62
    +( T_reg[61] ?  5'sd1 : -5'sd1)  // 61
    +( T_reg[60] ? -5'sd1 :  5'sd1)  // 60
    +( T_reg[59] ? -5'sd1 :  5'sd1)  // 59
    +( T_reg[58] ? -5'sd2 :  5'sd2)  // 58
    +( T_reg[57] ?  5'sd1 : -5'sd1)  // 57
    +( T_reg[56] ? -5'sd1 :  5'sd1)  // 56
    +( T_reg[55] ?  5'sd5 : -5'sd5)  // 55
    +( T_reg[54] ?  5'sd1 : -5'sd1)  // 54
    +( T_reg[53] ?  5'sd1 : -5'sd1)  // 53
    +( T_reg[52] ? -5'sd1 :  5'sd1)  // 52
    +( T_reg[51] ? -5'sd1 :  5'sd1)  // 51
    +( T_reg[50] ?  5'sd2 : -5'sd2)  // 50
    +( T_reg[49] ?  5'sd2 : -5'sd2)  // 49
    +( T_reg[48] ?  5'sd1 : -5'sd1)  // 48
    +( T_reg[47] ?  5'sd1 : -5'sd1)  // 47
    +( T_reg[46] ? -5'sd2 :  5'sd2)  // 46
    +( T_reg[45] ?  5'sd1 : -5'sd1)  // 45
    +( T_reg[44] ? -5'sd3 :  5'sd3)  // 44
    +( T_reg[43] ? -5'sd1 :  5'sd1)  // 43
    +( T_reg[42] ? -5'sd1 :  5'sd1)  // 42
    +( T_reg[41] ? -5'sd1 :  5'sd1)  // 41
    +( T_reg[40] ? -5'sd1 :  5'sd1)  // 40
    +( T_reg[39] ?  5'sd1 : -5'sd1)  // 39
    +( T_reg[38] ?  5'sd1 : -5'sd1)  // 38
    +( T_reg[37] ?  5'sd1 : -5'sd1)  // 37
    +( T_reg[36] ?  5'sd1 : -5'sd1)  // 36
    +( T_reg[35] ? -5'sd1 :  5'sd1)  // 35
    +( T_reg[34] ?  5'sd1 : -5'sd1)  // 34
    +( T_reg[33] ? -5'sd1 :  5'sd1)  // 33
    +( T_reg[32] ?  5'sd1 : -5'sd1)  // 32
    +( T_reg[31] ? -5'sd2 :  5'sd2)  // 31
    +( T_reg[30] ?  5'sd2 : -5'sd2)  // 30
    +( T_reg[29] ?  5'sd1 : -5'sd1)  // 29
    +( T_reg[28] ?  5'sd2 : -5'sd2)  // 28
    +( T_reg[27] ?  5'sd1 : -5'sd1)  // 27
    +( T_reg[26] ? -5'sd2 :  5'sd2)  // 26
    +( T_reg[25] ? -5'sd1 :  5'sd1)  // 25
    +( T_reg[24] ?  5'sd1 : -5'sd1)  // 24
    +( T_reg[23] ?  5'sd1 : -5'sd1)  // 23
    +( T_reg[22] ?  5'sd2 : -5'sd2)  // 22
    +( T_reg[21] ? -5'sd2 :  5'sd2)  // 21
    +( T_reg[20] ? -5'sd1 :  5'sd1)  // 20
    +( T_reg[19] ? -5'sd1 :  5'sd1)  // 19
    +( T_reg[18] ? -5'sd1 :  5'sd1)  // 18
    +( T_reg[17] ?  5'sd2 : -5'sd2)  // 17
    +( T_reg[16] ? -5'sd1 :  5'sd1)  // 16
    +( T_reg[15] ?  5'sd1 : -5'sd1)  // 15
    +( T_reg[14] ?  5'sd1 : -5'sd1)  // 14
    +( T_reg[13] ?  5'sd3 : -5'sd3)  // 13
    +( T_reg[12] ?  5'sd1 : -5'sd1)  // 12
    +( T_reg[11] ? -5'sd1 :  5'sd1)  // 11
    +( T_reg[10] ?  5'sd1 : -5'sd1)  // 10
    +( T_reg[9] ?  5'sd1 : -5'sd1)  // 9
    +( T_reg[8] ? -5'sd1 :  5'sd1)  // 8
    +( T_reg[7] ? -5'sd1 :  5'sd1)  // 7
    +( T_reg[6] ?  5'sd1 : -5'sd1)  // 6
    +( T_reg[5] ? -5'sd1 :  5'sd1)  // 5
    +( T_reg[4] ? -5'sd1 :  5'sd1)  // 4
    +( T_reg[3] ? -5'sd2 :  5'sd2)  // 3
    +( T_reg[2] ?  5'sd1 : -5'sd1)  // 2
    +( T_reg[1] ? -5'sd1 :  5'sd1)  // 1
    +( T_reg[0] ?  5'sd3 : -5'sd3)  // 0
  );

  wire signed [TH_WIDTH+8:0] acc_full = $signed(7 * C) + sum_terms;
  assign sat_out = $signed(acc_full) >>> 3;
  assign SOLVED  = (sat_out == $signed(C));

  reg                   read_active;
  reg                   read_active_d;
  reg [7:0] read_count;
  always @(posedge clk or posedge RESET) begin
    if (RESET) begin
      read_active   <= 1'b0;
      read_active_d <= 1'b0;
      read_count    <= 8'd0;
      T_READOUT     <= 1'b0;
    end else if (ENABLE) begin
      read_active_d <= READ;
      // start read on rising edge of READ
      if (READ & ~read_active_d)
        read_active <= 1'b1;
      // stop when READ deasserts or after NUM_CLS bits
      else if (~READ || (read_count == NUM_CLS-1))
        read_active <= 1'b0;

      if (read_active) begin
        T_READOUT <= T_reg[read_count];
        // increment but don't overflow
        if (read_count < NUM_CLS-1)
          read_count <= read_count + 1;
      end else begin
        read_count <= 8'd0;
      end
    end
  end
  wire ENABLE_INTERNAL = ENABLE && ~READ;
  solver u_solver (
    .clk        (clk),
    .RESET      (RESET),
    .ENABLE     (ENABLE_INTERNAL),
    .LOAD_T     (LOAD_T),
    .LOAD_NOISE (LOAD_NOISE),
    .RUN        (RUN),
    .T_IN       (T_IN),
    .NOISE_IN   (NOISE_IN),
    .T_reg      (T_reg)
  );

endmodule