`timescale 1ns/1ps
//-------------------------------------------------------------------------
// Verilog_files\solver_modules\uf20_02\solver_uf20_02.v - generated by generate_verilog_scripts.py
//-------------------------------------------------------------------------
module solver 
(
  input  wire                  clk, RESET, ENABLE, LOAD_T, LOAD_NOISE, RUN,
  input  wire                  T_IN,
  input  wire signed [15:0]   NOISE_IN,
  output reg  [209:0]    T_reg
);

  localparam integer NUM_CLS           = 210;
  localparam integer NUM_VAR           = 20;
  localparam integer MAX_COLOR         = 9;
  localparam integer MAX_COL_NNZ       = 32;
  localparam integer MAX_VAR_PER_COLOR = 3;
  localparam integer H_WIDTH           = 5;
  localparam integer TH_WIDTH          = 16;
  integer i, i_cls;
  reg [$clog2(NUM_CLS)-1:0]               t_load_count;
  reg [1:0]             noise_load_count;
  reg [$clog2(MAX_COLOR)-1:0]     current_color, next_color;
  reg [NUM_CLS-1:0]            T_next;
  reg [TH_WIDTH-1:0]           noisethld_vec [0:MAX_VAR_PER_COLOR-1];
  reg update;

  always @(posedge clk or posedge RESET) begin
    if (RESET) begin
      T_reg            <= {NUM_CLS{1'b0}};
      t_load_count     <= {($clog2(NUM_CLS)){1'b0}};
      noise_load_count <= {2{1'b0}};
      current_color    <= {($clog2(MAX_COLOR)){1'b0}};
      update <= 1'b0;
      for (i = 0; i < MAX_VAR_PER_COLOR; i = i + 1)
        noisethld_vec[i] <= {TH_WIDTH{1'b0}};
    end else if (ENABLE) begin
      if (LOAD_T) begin
        T_reg[t_load_count] <= T_IN;
        t_load_count       <= t_load_count + 1;
      end else if (LOAD_NOISE) begin
        noisethld_vec[noise_load_count] <= NOISE_IN;
        noise_load_count               <= noise_load_count + 1;
      end else if (RUN) begin
        update <= 1'b1;
        current_color <= next_color;
        // shift thresholds and inject new

        for (i = MAX_VAR_PER_COLOR-1; i > 0; i = i-1)
            noisethld_vec[i] <= noisethld_vec[i-1];
        noisethld_vec[0] <= NOISE_IN;
        T_reg         <= T_next;
      end
    end
  end

  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_0 = {(T_reg[0] ? -5'sd1 : 5'sd0), (T_reg[1] ? 5'sd1 : 5'sd0), (T_reg[2] ? 5'sd1 : 5'sd0), (T_reg[3] ? -5'sd1 : 5'sd0), (T_reg[4] ? -5'sd1 : 5'sd0), (T_reg[5] ? 5'sd1 : 5'sd0), (T_reg[6] ? -5'sd1 : 5'sd0), (T_reg[7] ? -5'sd2 : 5'sd0), (T_reg[8] ? -5'sd1 : 5'sd0), (T_reg[9] ? 5'sd1 : 5'sd0), (T_reg[10] ? 5'sd1 : 5'sd0), (T_reg[11] ? 5'sd1 : 5'sd0), (T_reg[12] ? 5'sd1 : 5'sd0), (T_reg[13] ? -5'sd1 : 5'sd0), (T_reg[14] ? -5'sd1 : 5'sd0), (T_reg[15] ? -5'sd1 : 5'sd0), (T_reg[16] ? -5'sd1 : 5'sd0), (T_reg[17] ? 5'sd1 : 5'sd0), (T_reg[18] ? -5'sd1 : 5'sd0), (T_reg[19] ? -5'sd1 : 5'sd0), (T_reg[20] ? 5'sd1 : 5'sd0), (T_reg[21] ? 5'sd1 : 5'sd0), (T_reg[22] ? 5'sd1 : 5'sd0), (T_reg[23] ? -5'sd1 : 5'sd0), (T_reg[24] ? -5'sd1 : 5'sd0), (T_reg[25] ? -5'sd2 : 5'sd0), (T_reg[26] ? 5'sd1 : 5'sd0), (T_reg[27] ? -5'sd1 : 5'sd0), (T_reg[28] ? -5'sd1 : 5'sd0), (T_reg[29] ? -5'sd1 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_1 = {(T_reg[1] ? 5'sd1 : 5'sd0), (T_reg[2] ? 5'sd1 : 5'sd0), (T_reg[30] ? -5'sd3 : 5'sd0), (T_reg[31] ? 5'sd1 : 5'sd0), (T_reg[32] ? -5'sd1 : 5'sd0), (T_reg[33] ? -5'sd1 : 5'sd0), (T_reg[34] ? -5'sd1 : 5'sd0), (T_reg[35] ? 5'sd1 : 5'sd0), (T_reg[36] ? 5'sd1 : 5'sd0), (T_reg[37] ? 5'sd1 : 5'sd0), (T_reg[38] ? 5'sd1 : 5'sd0), (T_reg[39] ? -5'sd1 : 5'sd0), (T_reg[40] ? 5'sd1 : 5'sd0), (T_reg[41] ? -5'sd1 : 5'sd0), (T_reg[42] ? -5'sd1 : 5'sd0), (T_reg[43] ? 5'sd1 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_2 = {(T_reg[3] ? -5'sd1 : 5'sd0), (T_reg[4] ? -5'sd1 : 5'sd0), (T_reg[44] ? 5'sd2 : 5'sd0), (T_reg[45] ? 5'sd2 : 5'sd0), (T_reg[46] ? -5'sd1 : 5'sd0), (T_reg[47] ? 5'sd1 : 5'sd0), (T_reg[48] ? -5'sd3 : 5'sd0), (T_reg[49] ? -5'sd1 : 5'sd0), (T_reg[50] ? 5'sd1 : 5'sd0), (T_reg[51] ? 5'sd1 : 5'sd0), (T_reg[52] ? -5'sd1 : 5'sd0), (T_reg[53] ? -5'sd1 : 5'sd0), (T_reg[54] ? 5'sd1 : 5'sd0), (T_reg[55] ? 5'sd2 : 5'sd0), (T_reg[56] ? 5'sd1 : 5'sd0), (T_reg[57] ? -5'sd1 : 5'sd0), (T_reg[58] ? 5'sd1 : 5'sd0), (T_reg[59] ? -5'sd2 : 5'sd0), (T_reg[60] ? 5'sd1 : 5'sd0), (T_reg[61] ? -5'sd1 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_3 = {(T_reg[62] ? -5'sd1 : 5'sd0), (T_reg[63] ? 5'sd1 : 5'sd0), (T_reg[64] ? -5'sd1 : 5'sd0), (T_reg[65] ? 5'sd1 : 5'sd0), (T_reg[66] ? -5'sd1 : 5'sd0), (T_reg[67] ? -5'sd2 : 5'sd0), (T_reg[68] ? 5'sd1 : 5'sd0), (T_reg[69] ? 5'sd1 : 5'sd0), (T_reg[70] ? -5'sd1 : 5'sd0), (T_reg[71] ? 5'sd2 : 5'sd0), (T_reg[72] ? -5'sd1 : 5'sd0), (T_reg[73] ? 5'sd1 : 5'sd0), (T_reg[74] ? -5'sd1 : 5'sd0), (T_reg[75] ? -5'sd1 : 5'sd0), (T_reg[76] ? -5'sd2 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_4 = {(T_reg[5] ? 5'sd1 : 5'sd0), (T_reg[6] ? -5'sd1 : 5'sd0), (T_reg[77] ? 5'sd5 : 5'sd0), (T_reg[78] ? 5'sd3 : 5'sd0), (T_reg[79] ? 5'sd1 : 5'sd0), (T_reg[80] ? 5'sd1 : 5'sd0), (T_reg[81] ? 5'sd1 : 5'sd0), (T_reg[82] ? -5'sd1 : 5'sd0), (T_reg[83] ? -5'sd1 : 5'sd0), (T_reg[84] ? 5'sd1 : 5'sd0), (T_reg[85] ? -5'sd1 : 5'sd0), (T_reg[86] ? 5'sd1 : 5'sd0), (T_reg[87] ? -5'sd1 : 5'sd0), (T_reg[88] ? 5'sd1 : 5'sd0), (T_reg[89] ? -5'sd1 : 5'sd0), (T_reg[90] ? 5'sd1 : 5'sd0), (T_reg[91] ? 5'sd2 : 5'sd0), (T_reg[92] ? -5'sd1 : 5'sd0), (T_reg[93] ? 5'sd2 : 5'sd0), (T_reg[94] ? -5'sd1 : 5'sd0), (T_reg[95] ? 5'sd1 : 5'sd0), (T_reg[96] ? -5'sd1 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_5 = {(T_reg[7] ? -5'sd2 : 5'sd0), (T_reg[8] ? -5'sd1 : 5'sd0), (T_reg[9] ? 5'sd1 : 5'sd0), (T_reg[31] ? 5'sd1 : 5'sd0), (T_reg[32] ? -5'sd1 : 5'sd0), (T_reg[45] ? 5'sd2 : 5'sd0), (T_reg[46] ? -5'sd1 : 5'sd0), (T_reg[47] ? 5'sd1 : 5'sd0), (T_reg[63] ? 5'sd1 : 5'sd0), (T_reg[64] ? -5'sd1 : 5'sd0), (T_reg[78] ? 5'sd3 : 5'sd0), (T_reg[79] ? 5'sd1 : 5'sd0), (T_reg[97] ? -5'sd5 : 5'sd0), (T_reg[98] ? 5'sd2 : 5'sd0), (T_reg[99] ? 5'sd1 : 5'sd0), (T_reg[100] ? 5'sd1 : 5'sd0), (T_reg[101] ? 5'sd1 : 5'sd0), (T_reg[102] ? -5'sd1 : 5'sd0), (T_reg[103] ? 5'sd1 : 5'sd0), (T_reg[104] ? -5'sd1 : 5'sd0), (T_reg[105] ? 5'sd1 : 5'sd0), (T_reg[106] ? 5'sd1 : 5'sd0), (T_reg[107] ? 5'sd1 : 5'sd0), (T_reg[108] ? 5'sd1 : 5'sd0), (T_reg[109] ? -5'sd1 : 5'sd0), (T_reg[110] ? -5'sd1 : 5'sd0), (T_reg[111] ? 5'sd2 : 5'sd0), (T_reg[112] ? 5'sd1 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_6 = {(T_reg[4] ? -5'sd1 : 5'sd0), (T_reg[10] ? 5'sd1 : 5'sd0), (T_reg[11] ? 5'sd1 : 5'sd0), (T_reg[12] ? 5'sd1 : 5'sd0), (T_reg[31] ? 5'sd1 : 5'sd0), (T_reg[33] ? -5'sd1 : 5'sd0), (T_reg[46] ? -5'sd1 : 5'sd0), (T_reg[48] ? -5'sd3 : 5'sd0), (T_reg[49] ? -5'sd1 : 5'sd0), (T_reg[50] ? 5'sd1 : 5'sd0), (T_reg[51] ? 5'sd1 : 5'sd0), (T_reg[65] ? 5'sd1 : 5'sd0), (T_reg[66] ? -5'sd1 : 5'sd0), (T_reg[80] ? 5'sd1 : 5'sd0), (T_reg[81] ? 5'sd1 : 5'sd0), (T_reg[98] ? 5'sd2 : 5'sd0), (T_reg[113] ? 5'sd5 : 5'sd0), (T_reg[114] ? 5'sd1 : 5'sd0), (T_reg[115] ? 5'sd1 : 5'sd0), (T_reg[116] ? -5'sd1 : 5'sd0), (T_reg[117] ? -5'sd1 : 5'sd0), (T_reg[118] ? 5'sd1 : 5'sd0), (T_reg[119] ? 5'sd1 : 5'sd0), (T_reg[120] ? -5'sd1 : 5'sd0), (T_reg[121] ? 5'sd1 : 5'sd0), (T_reg[122] ? -5'sd2 : 5'sd0), (T_reg[123] ? 5'sd1 : 5'sd0), (T_reg[124] ? 5'sd1 : 5'sd0), (T_reg[125] ? 5'sd1 : 5'sd0), (T_reg[126] ? -5'sd2 : 5'sd0), (T_reg[127] ? -5'sd1 : 5'sd0), {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_7 = {(T_reg[13] ? -5'sd1 : 5'sd0), (T_reg[14] ? -5'sd1 : 5'sd0), (T_reg[52] ? -5'sd1 : 5'sd0), (T_reg[53] ? -5'sd1 : 5'sd0), (T_reg[67] ? -5'sd2 : 5'sd0), (T_reg[68] ? 5'sd1 : 5'sd0), (T_reg[69] ? 5'sd1 : 5'sd0), (T_reg[82] ? -5'sd1 : 5'sd0), (T_reg[83] ? -5'sd1 : 5'sd0), (T_reg[99] ? 5'sd1 : 5'sd0), (T_reg[100] ? 5'sd1 : 5'sd0), (T_reg[114] ? 5'sd1 : 5'sd0), (T_reg[115] ? 5'sd1 : 5'sd0), (T_reg[128] ? 5'sd4 : 5'sd0), (T_reg[129] ? 5'sd1 : 5'sd0), (T_reg[130] ? -5'sd3 : 5'sd0), (T_reg[131] ? -5'sd1 : 5'sd0), (T_reg[132] ? -5'sd1 : 5'sd0), (T_reg[133] ? 5'sd1 : 5'sd0), (T_reg[134] ? -5'sd1 : 5'sd0), (T_reg[135] ? 5'sd1 : 5'sd0), (T_reg[136] ? 5'sd5 : 5'sd0), (T_reg[137] ? 5'sd1 : 5'sd0), (T_reg[138] ? -5'sd2 : 5'sd0), (T_reg[139] ? -5'sd2 : 5'sd0), (T_reg[140] ? -5'sd1 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_8 = {(T_reg[15] ? -5'sd1 : 5'sd0), (T_reg[16] ? -5'sd1 : 5'sd0), (T_reg[17] ? 5'sd1 : 5'sd0), (T_reg[18] ? -5'sd1 : 5'sd0), (T_reg[34] ? -5'sd1 : 5'sd0), (T_reg[35] ? 5'sd1 : 5'sd0), (T_reg[53] ? -5'sd1 : 5'sd0), (T_reg[54] ? 5'sd1 : 5'sd0), (T_reg[84] ? 5'sd1 : 5'sd0), (T_reg[85] ? -5'sd1 : 5'sd0), (T_reg[116] ? -5'sd1 : 5'sd0), (T_reg[117] ? -5'sd1 : 5'sd0), (T_reg[129] ? 5'sd1 : 5'sd0), (T_reg[141] ? 5'sd2 : 5'sd0), (T_reg[142] ? 5'sd1 : 5'sd0), (T_reg[143] ? -5'sd1 : 5'sd0), (T_reg[144] ? -5'sd1 : 5'sd0), (T_reg[145] ? 5'sd1 : 5'sd0), (T_reg[146] ? 5'sd1 : 5'sd0), (T_reg[147] ? -5'sd2 : 5'sd0), (T_reg[148] ? -5'sd1 : 5'sd0), (T_reg[149] ? 5'sd1 : 5'sd0), (T_reg[150] ? -5'sd3 : 5'sd0), (T_reg[151] ? 5'sd3 : 5'sd0), (T_reg[152] ? 5'sd2 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_9 = {(T_reg[14] ? -5'sd1 : 5'sd0), (T_reg[19] ? -5'sd1 : 5'sd0), (T_reg[32] ? -5'sd1 : 5'sd0), (T_reg[36] ? 5'sd1 : 5'sd0), (T_reg[68] ? 5'sd1 : 5'sd0), (T_reg[70] ? -5'sd1 : 5'sd0), (T_reg[86] ? 5'sd1 : 5'sd0), (T_reg[87] ? -5'sd1 : 5'sd0), (T_reg[101] ? 5'sd1 : 5'sd0), (T_reg[118] ? 5'sd1 : 5'sd0), (T_reg[119] ? 5'sd1 : 5'sd0), (T_reg[130] ? -5'sd3 : 5'sd0), (T_reg[131] ? -5'sd1 : 5'sd0), (T_reg[153] ? -5'sd2 : 5'sd0), (T_reg[154] ? -5'sd1 : 5'sd0), (T_reg[155] ? -5'sd1 : 5'sd0), (T_reg[156] ? 5'sd2 : 5'sd0), (T_reg[157] ? 5'sd1 : 5'sd0), (T_reg[158] ? -5'sd1 : 5'sd0), (T_reg[159] ? 5'sd1 : 5'sd0), (T_reg[160] ? -5'sd1 : 5'sd0), (T_reg[161] ? 5'sd1 : 5'sd0), (T_reg[162] ? -5'sd1 : 5'sd0), (T_reg[163] ? 5'sd1 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_10 = {(T_reg[20] ? 5'sd1 : 5'sd0), (T_reg[21] ? 5'sd1 : 5'sd0), (T_reg[22] ? 5'sd1 : 5'sd0), (T_reg[23] ? -5'sd1 : 5'sd0), (T_reg[37] ? 5'sd1 : 5'sd0), (T_reg[38] ? 5'sd1 : 5'sd0), (T_reg[70] ? -5'sd1 : 5'sd0), (T_reg[71] ? 5'sd2 : 5'sd0), (T_reg[72] ? -5'sd1 : 5'sd0), (T_reg[132] ? -5'sd1 : 5'sd0), (T_reg[133] ? 5'sd1 : 5'sd0), (T_reg[142] ? 5'sd1 : 5'sd0), (T_reg[143] ? -5'sd1 : 5'sd0), (T_reg[154] ? -5'sd1 : 5'sd0), (T_reg[164] ? -5'sd1 : 5'sd0), (T_reg[165] ? 5'sd4 : 5'sd0), (T_reg[166] ? 5'sd1 : 5'sd0), (T_reg[167] ? 5'sd1 : 5'sd0), (T_reg[168] ? -5'sd1 : 5'sd0), (T_reg[169] ? 5'sd1 : 5'sd0), (T_reg[170] ? -5'sd1 : 5'sd0), (T_reg[171] ? 5'sd3 : 5'sd0), (T_reg[172] ? -5'sd1 : 5'sd0), (T_reg[173] ? -5'sd1 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_11 = {(T_reg[16] ? -5'sd1 : 5'sd0), (T_reg[24] ? -5'sd1 : 5'sd0), (T_reg[55] ? 5'sd2 : 5'sd0), (T_reg[56] ? 5'sd1 : 5'sd0), (T_reg[57] ? -5'sd1 : 5'sd0), (T_reg[64] ? -5'sd1 : 5'sd0), (T_reg[72] ? -5'sd1 : 5'sd0), (T_reg[80] ? 5'sd1 : 5'sd0), (T_reg[88] ? 5'sd1 : 5'sd0), (T_reg[102] ? -5'sd1 : 5'sd0), (T_reg[103] ? 5'sd1 : 5'sd0), (T_reg[104] ? -5'sd1 : 5'sd0), (T_reg[120] ? -5'sd1 : 5'sd0), (T_reg[134] ? -5'sd1 : 5'sd0), (T_reg[135] ? 5'sd1 : 5'sd0), (T_reg[144] ? -5'sd1 : 5'sd0), (T_reg[154] ? -5'sd1 : 5'sd0), (T_reg[155] ? -5'sd1 : 5'sd0), (T_reg[174] ? -5'sd2 : 5'sd0), (T_reg[175] ? -5'sd1 : 5'sd0), (T_reg[176] ? 5'sd1 : 5'sd0), (T_reg[177] ? -5'sd1 : 5'sd0), (T_reg[178] ? -5'sd1 : 5'sd0), (T_reg[179] ? 5'sd1 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_12 = {(T_reg[8] ? -5'sd1 : 5'sd0), (T_reg[21] ? 5'sd1 : 5'sd0), (T_reg[38] ? 5'sd1 : 5'sd0), (T_reg[39] ? -5'sd1 : 5'sd0), (T_reg[47] ? 5'sd1 : 5'sd0), (T_reg[56] ? 5'sd1 : 5'sd0), (T_reg[79] ? 5'sd1 : 5'sd0), (T_reg[89] ? -5'sd1 : 5'sd0), (T_reg[105] ? 5'sd1 : 5'sd0), (T_reg[106] ? 5'sd1 : 5'sd0), (T_reg[107] ? 5'sd1 : 5'sd0), (T_reg[116] ? -5'sd1 : 5'sd0), (T_reg[121] ? 5'sd1 : 5'sd0), (T_reg[145] ? 5'sd1 : 5'sd0), (T_reg[156] ? 5'sd2 : 5'sd0), (T_reg[157] ? 5'sd1 : 5'sd0), (T_reg[158] ? -5'sd1 : 5'sd0), (T_reg[165] ? 5'sd4 : 5'sd0), (T_reg[166] ? 5'sd1 : 5'sd0), (T_reg[167] ? 5'sd1 : 5'sd0), (T_reg[175] ? -5'sd1 : 5'sd0), (T_reg[180] ? -5'sd8 : 5'sd0), (T_reg[181] ? 5'sd2 : 5'sd0), (T_reg[182] ? -5'sd1 : 5'sd0), (T_reg[183] ? -5'sd1 : 5'sd0), (T_reg[184] ? -5'sd2 : 5'sd0), (T_reg[185] ? 5'sd1 : 5'sd0), (T_reg[186] ? -5'sd1 : 5'sd0), (T_reg[187] ? 5'sd1 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_13 = {(T_reg[1] ? 5'sd1 : 5'sd0), (T_reg[6] ? -5'sd1 : 5'sd0), (T_reg[17] ? 5'sd1 : 5'sd0), (T_reg[25] ? -5'sd2 : 5'sd0), (T_reg[26] ? 5'sd1 : 5'sd0), (T_reg[40] ? 5'sd1 : 5'sd0), (T_reg[49] ? -5'sd1 : 5'sd0), (T_reg[58] ? 5'sd1 : 5'sd0), (T_reg[90] ? 5'sd1 : 5'sd0), (T_reg[122] ? -5'sd2 : 5'sd0), (T_reg[123] ? 5'sd1 : 5'sd0), (T_reg[146] ? 5'sd1 : 5'sd0), (T_reg[166] ? 5'sd1 : 5'sd0), (T_reg[168] ? -5'sd1 : 5'sd0), (T_reg[181] ? 5'sd2 : 5'sd0), (T_reg[182] ? -5'sd1 : 5'sd0), (T_reg[188] ? 5'sd2 : 5'sd0), (T_reg[189] ? -5'sd1 : 5'sd0), (T_reg[190] ? 5'sd2 : 5'sd0), (T_reg[191] ? -5'sd3 : 5'sd0), (T_reg[192] ? -5'sd1 : 5'sd0), (T_reg[193] ? -5'sd2 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_14 = {(T_reg[26] ? 5'sd1 : 5'sd0), (T_reg[27] ? -5'sd1 : 5'sd0), (T_reg[103] ? 5'sd1 : 5'sd0), (T_reg[108] ? 5'sd1 : 5'sd0), (T_reg[157] ? 5'sd1 : 5'sd0), (T_reg[159] ? 5'sd1 : 5'sd0), (T_reg[176] ? 5'sd1 : 5'sd0), (T_reg[183] ? -5'sd1 : 5'sd0), (T_reg[189] ? -5'sd1 : 5'sd0), (T_reg[194] ? 5'sd1 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_15 = {(T_reg[41] ? -5'sd1 : 5'sd0), (T_reg[42] ? -5'sd1 : 5'sd0), (T_reg[50] ? 5'sd1 : 5'sd0), (T_reg[59] ? -5'sd2 : 5'sd0), (T_reg[60] ? 5'sd1 : 5'sd0), (T_reg[83] ? -5'sd1 : 5'sd0), (T_reg[86] ? 5'sd1 : 5'sd0), (T_reg[91] ? 5'sd2 : 5'sd0), (T_reg[100] ? 5'sd1 : 5'sd0), (T_reg[109] ? -5'sd1 : 5'sd0), (T_reg[123] ? 5'sd1 : 5'sd0), (T_reg[124] ? 5'sd1 : 5'sd0), (T_reg[125] ? 5'sd1 : 5'sd0), (T_reg[136] ? 5'sd5 : 5'sd0), (T_reg[137] ? 5'sd1 : 5'sd0), (T_reg[146] ? 5'sd1 : 5'sd0), (T_reg[147] ? -5'sd2 : 5'sd0), (T_reg[148] ? -5'sd1 : 5'sd0), (T_reg[160] ? -5'sd1 : 5'sd0), (T_reg[167] ? 5'sd1 : 5'sd0), (T_reg[169] ? 5'sd1 : 5'sd0), (T_reg[184] ? -5'sd2 : 5'sd0), (T_reg[185] ? 5'sd1 : 5'sd0), (T_reg[190] ? 5'sd2 : 5'sd0), (T_reg[195] ? -5'sd3 : 5'sd0), (T_reg[196] ? -5'sd2 : 5'sd0), (T_reg[197] ? -5'sd1 : 5'sd0), (T_reg[198] ? 5'sd1 : 5'sd0), (T_reg[199] ? 5'sd1 : 5'sd0), (T_reg[200] ? -5'sd1 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_16 = {(T_reg[11] ? 5'sd1 : 5'sd0), (T_reg[22] ? 5'sd1 : 5'sd0), (T_reg[24] ? -5'sd1 : 5'sd0), (T_reg[28] ? -5'sd1 : 5'sd0), (T_reg[40] ? 5'sd1 : 5'sd0), (T_reg[43] ? 5'sd1 : 5'sd0), (T_reg[60] ? 5'sd1 : 5'sd0), (T_reg[61] ? -5'sd1 : 5'sd0), (T_reg[66] ? -5'sd1 : 5'sd0), (T_reg[73] ? 5'sd1 : 5'sd0), (T_reg[81] ? 5'sd1 : 5'sd0), (T_reg[92] ? -5'sd1 : 5'sd0), (T_reg[104] ? -5'sd1 : 5'sd0), (T_reg[110] ? -5'sd1 : 5'sd0), (T_reg[125] ? 5'sd1 : 5'sd0), (T_reg[144] ? -5'sd1 : 5'sd0), (T_reg[149] ? 5'sd1 : 5'sd0), (T_reg[158] ? -5'sd1 : 5'sd0), (T_reg[161] ? 5'sd1 : 5'sd0), (T_reg[170] ? -5'sd1 : 5'sd0), (T_reg[177] ? -5'sd1 : 5'sd0), (T_reg[182] ? -5'sd1 : 5'sd0), (T_reg[191] ? -5'sd3 : 5'sd0), (T_reg[192] ? -5'sd1 : 5'sd0), (T_reg[196] ? -5'sd2 : 5'sd0), (T_reg[201] ? -5'sd2 : 5'sd0), (T_reg[202] ? -5'sd1 : 5'sd0), (T_reg[203] ? -5'sd1 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_17 = {(T_reg[18] ? -5'sd1 : 5'sd0), (T_reg[29] ? -5'sd1 : 5'sd0), (T_reg[74] ? -5'sd1 : 5'sd0), (T_reg[75] ? -5'sd1 : 5'sd0), (T_reg[85] ? -5'sd1 : 5'sd0), (T_reg[93] ? 5'sd2 : 5'sd0), (T_reg[94] ? -5'sd1 : 5'sd0), (T_reg[114] ? 5'sd1 : 5'sd0), (T_reg[126] ? -5'sd2 : 5'sd0), (T_reg[127] ? -5'sd1 : 5'sd0), (T_reg[131] ? -5'sd1 : 5'sd0), (T_reg[133] ? 5'sd1 : 5'sd0), (T_reg[135] ? 5'sd1 : 5'sd0), (T_reg[138] ? -5'sd2 : 5'sd0), (T_reg[143] ? -5'sd1 : 5'sd0), (T_reg[150] ? -5'sd3 : 5'sd0), (T_reg[162] ? -5'sd1 : 5'sd0), (T_reg[168] ? -5'sd1 : 5'sd0), (T_reg[171] ? 5'sd3 : 5'sd0), (T_reg[178] ? -5'sd1 : 5'sd0), (T_reg[185] ? 5'sd1 : 5'sd0), (T_reg[186] ? -5'sd1 : 5'sd0), (T_reg[192] ? -5'sd1 : 5'sd0), (T_reg[193] ? -5'sd2 : 5'sd0), (T_reg[197] ? -5'sd1 : 5'sd0), (T_reg[202] ? -5'sd1 : 5'sd0), (T_reg[204] ? -5'sd1 : 5'sd0), (T_reg[205] ? -5'sd1 : 5'sd0), (T_reg[206] ? -5'sd1 : 5'sd0), (T_reg[207] ? -5'sd1 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_18 = {(T_reg[2] ? 5'sd1 : 5'sd0), (T_reg[9] ? 5'sd1 : 5'sd0), (T_reg[39] ? -5'sd1 : 5'sd0), (T_reg[51] ? 5'sd1 : 5'sd0), (T_reg[57] ? -5'sd1 : 5'sd0), (T_reg[69] ? 5'sd1 : 5'sd0), (T_reg[75] ? -5'sd1 : 5'sd0), (T_reg[76] ? -5'sd2 : 5'sd0), (T_reg[94] ? -5'sd1 : 5'sd0), (T_reg[95] ? 5'sd1 : 5'sd0), (T_reg[106] ? 5'sd1 : 5'sd0), (T_reg[111] ? 5'sd2 : 5'sd0), (T_reg[115] ? 5'sd1 : 5'sd0), (T_reg[117] ? -5'sd1 : 5'sd0), (T_reg[127] ? -5'sd1 : 5'sd0), (T_reg[139] ? -5'sd2 : 5'sd0), (T_reg[148] ? -5'sd1 : 5'sd0), (T_reg[149] ? 5'sd1 : 5'sd0), (T_reg[151] ? 5'sd3 : 5'sd0), (T_reg[159] ? 5'sd1 : 5'sd0), (T_reg[163] ? 5'sd1 : 5'sd0), (T_reg[172] ? -5'sd1 : 5'sd0), (T_reg[173] ? -5'sd1 : 5'sd0), (T_reg[179] ? 5'sd1 : 5'sd0), (T_reg[194] ? 5'sd1 : 5'sd0), (T_reg[197] ? -5'sd1 : 5'sd0), (T_reg[198] ? 5'sd1 : 5'sd0), (T_reg[199] ? 5'sd1 : 5'sd0), (T_reg[203] ? -5'sd1 : 5'sd0), (T_reg[205] ? -5'sd1 : 5'sd0), (T_reg[206] ? -5'sd1 : 5'sd0), (T_reg[208] ? 5'sd6 : 5'sd0)};
  wire signed [H_WIDTH*MAX_COL_NNZ-1:0] q_pp_flat_19 = {(T_reg[12] ? 5'sd1 : 5'sd0), (T_reg[23] ? -5'sd1 : 5'sd0), (T_reg[35] ? 5'sd1 : 5'sd0), (T_reg[42] ? -5'sd1 : 5'sd0), (T_reg[87] ? -5'sd1 : 5'sd0), (T_reg[89] ? -5'sd1 : 5'sd0), (T_reg[95] ? 5'sd1 : 5'sd0), (T_reg[96] ? -5'sd1 : 5'sd0), (T_reg[107] ? 5'sd1 : 5'sd0), (T_reg[112] ? 5'sd1 : 5'sd0), (T_reg[119] ? 5'sd1 : 5'sd0), (T_reg[137] ? 5'sd1 : 5'sd0), (T_reg[140] ? -5'sd1 : 5'sd0), (T_reg[145] ? 5'sd1 : 5'sd0), (T_reg[152] ? 5'sd2 : 5'sd0), (T_reg[173] ? -5'sd1 : 5'sd0), (T_reg[187] ? 5'sd1 : 5'sd0), (T_reg[199] ? 5'sd1 : 5'sd0), (T_reg[200] ? -5'sd1 : 5'sd0), (T_reg[206] ? -5'sd1 : 5'sd0), (T_reg[207] ? -5'sd1 : 5'sd0), (T_reg[209] ? -5'sd10 : 5'sd0), {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}, {H_WIDTH{1'b0}}};

  reg signed [H_WIDTH*MAX_COL_NNZ-1:0] q_add_in [0:MAX_VAR_PER_COLOR-1];
  always @* begin
    case (current_color)
      0: begin q_add_in[0] = q_pp_flat_13; q_add_in[1] = q_pp_flat_18; q_add_in[2] = {H_WIDTH*MAX_COL_NNZ{1'b0}}; end
      1: begin q_add_in[0] = q_pp_flat_0; q_add_in[1] = q_pp_flat_3; q_add_in[2] = q_pp_flat_15;  end
      2: begin q_add_in[0] = q_pp_flat_6; q_add_in[1] = q_pp_flat_10; q_add_in[2] = q_pp_flat_14;  end
      3: begin q_add_in[0] = q_pp_flat_7; q_add_in[1] = q_pp_flat_12; q_add_in[2] = {H_WIDTH*MAX_COL_NNZ{1'b0}}; end
      4: begin q_add_in[0] = q_pp_flat_8; q_add_in[1] = q_pp_flat_9; q_add_in[2] = {H_WIDTH*MAX_COL_NNZ{1'b0}}; end
      5: begin q_add_in[0] = q_pp_flat_16; q_add_in[1] = q_pp_flat_19; q_add_in[2] = {H_WIDTH*MAX_COL_NNZ{1'b0}}; end
      6: begin q_add_in[0] = q_pp_flat_5; q_add_in[1] = q_pp_flat_17; q_add_in[2] = {H_WIDTH*MAX_COL_NNZ{1'b0}}; end
      7: begin q_add_in[0] = q_pp_flat_1; q_add_in[1] = q_pp_flat_11; q_add_in[2] = {H_WIDTH*MAX_COL_NNZ{1'b0}}; end
      8: begin q_add_in[0] = q_pp_flat_2; q_add_in[1] = q_pp_flat_4; q_add_in[2] = {H_WIDTH*MAX_COL_NNZ{1'b0}}; end
      default: begin
        q_add_in[0] = {H_WIDTH*MAX_COL_NNZ{1'b0}};
        q_add_in[1] = {H_WIDTH*MAX_COL_NNZ{1'b0}};
        q_add_in[2] = {H_WIDTH*MAX_COL_NNZ{1'b0}};
      end
    endcase
  end

  wire signed [TH_WIDTH-1:0] q_cal [0:MAX_VAR_PER_COLOR-1];
  adder_tree #(.IN_WIDTH(H_WIDTH), .N_INPUTS(MAX_COL_NNZ), .OUT_WIDTH(TH_WIDTH)) u_at_0 (.in_terms_flat(q_add_in[0]), .sum_out(q_cal[0]));
  adder_tree #(.IN_WIDTH(H_WIDTH), .N_INPUTS(MAX_COL_NNZ), .OUT_WIDTH(TH_WIDTH)) u_at_1 (.in_terms_flat(q_add_in[1]), .sum_out(q_cal[1]));
  adder_tree #(.IN_WIDTH(H_WIDTH), .N_INPUTS(MAX_COL_NNZ), .OUT_WIDTH(TH_WIDTH)) u_at_2 (.in_terms_flat(q_add_in[2]), .sum_out(q_cal[2]));

  reg [TH_WIDTH-1:0] noisethld_adj [0:MAX_VAR_PER_COLOR-1];
  integer j;
  always @* begin
    for (j = 0; j < MAX_VAR_PER_COLOR; j = j + 1)
      noisethld_adj[j] = {TH_WIDTH{1'b0}};
    case (current_color)
      0: begin
        noisethld_adj[0] = noisethld_vec[0] + 0;
        noisethld_adj[1] = noisethld_vec[1] + 8;
      end
      1: begin
        noisethld_adj[0] = noisethld_vec[0] + -8;
        noisethld_adj[1] = noisethld_vec[1] + -4;
        noisethld_adj[2] = noisethld_vec[2] + 4;
      end
      2: begin
        noisethld_adj[0] = noisethld_vec[0] + 8;
        noisethld_adj[1] = noisethld_vec[1] + 8;
        noisethld_adj[2] = noisethld_vec[2] + 4;
      end
      3: begin
        noisethld_adj[0] = noisethld_vec[0] + 0;
        noisethld_adj[1] = noisethld_vec[1] + 4;
      end
      4: begin
        noisethld_adj[0] = noisethld_vec[0] + 0;
        noisethld_adj[1] = noisethld_vec[1] + -4;
      end
      5: begin
        noisethld_adj[0] = noisethld_vec[0] + -12;
        noisethld_adj[1] = noisethld_vec[1] + -8;
      end
      6: begin
        noisethld_adj[0] = noisethld_vec[0] + 8;
        noisethld_adj[1] = noisethld_vec[1] + -20;
      end
      7: begin
        noisethld_adj[0] = noisethld_vec[0] + 0;
        noisethld_adj[1] = noisethld_vec[1] + -8;
      end
      8: begin
        noisethld_adj[0] = noisethld_vec[0] + 0;
        noisethld_adj[1] = noisethld_vec[1] + 12;
      end
      default: ;
    endcase
  end

  wire q_color [0:MAX_VAR_PER_COLOR-1];
  genvar gi;
  generate for (gi = 0; gi < MAX_VAR_PER_COLOR; gi = gi + 1) begin
      assign q_color[gi] = ((q_cal[gi]<<<1) < $signed(noisethld_adj[gi]));
    end endgenerate

  reg [NUM_VAR-1:0] q_vector_r;
  always @* begin
    q_vector_r = {NUM_VAR{1'b0}};
    case (current_color)
      0: begin q_vector_r[13] = q_color[0]; q_vector_r[18] = q_color[1]; end
      1: begin q_vector_r[0] = q_color[0]; q_vector_r[3] = q_color[1]; q_vector_r[15] = q_color[2]; end
      2: begin q_vector_r[6] = q_color[0]; q_vector_r[10] = q_color[1]; q_vector_r[14] = q_color[2]; end
      3: begin q_vector_r[7] = q_color[0]; q_vector_r[12] = q_color[1]; end
      4: begin q_vector_r[8] = q_color[0]; q_vector_r[9] = q_color[1]; end
      5: begin q_vector_r[16] = q_color[0]; q_vector_r[19] = q_color[1]; end
      6: begin q_vector_r[5] = q_color[0]; q_vector_r[17] = q_color[1]; end
      7: begin q_vector_r[1] = q_color[0]; q_vector_r[11] = q_color[1]; end
      8: begin q_vector_r[2] = q_color[0]; q_vector_r[4] = q_color[1]; end
      default: q_vector_r = {NUM_VAR{1'b0}};
    endcase
  end
  wire [NUM_VAR-1:0] q_vector = q_vector_r;

  wire [NUM_CLS-1:0] sigma;
  assign sigma[0] = q_vector[0];
  assign sigma[1] = q_vector[0] ^ q_vector[1] ^ q_vector[13];
  assign sigma[2] = q_vector[0] ^ q_vector[1] ^ q_vector[18];
  assign sigma[3] = q_vector[0] ^ q_vector[2];
  assign sigma[4] = q_vector[0] ^ q_vector[2] ^ q_vector[6];
  assign sigma[5] = q_vector[0] ^ q_vector[4];
  assign sigma[6] = q_vector[0] ^ q_vector[4] ^ q_vector[13];
  assign sigma[7] = q_vector[0] ^ q_vector[5];
  assign sigma[8] = q_vector[0] ^ q_vector[5] ^ q_vector[12];
  assign sigma[9] = q_vector[0] ^ q_vector[5] ^ q_vector[18];
  assign sigma[10] = q_vector[0] ^ q_vector[6];
  assign sigma[11] = q_vector[0] ^ q_vector[6] ^ q_vector[16];
  assign sigma[12] = q_vector[0] ^ q_vector[6] ^ q_vector[19];
  assign sigma[13] = q_vector[0] ^ q_vector[7];
  assign sigma[14] = q_vector[0] ^ q_vector[7] ^ q_vector[9];
  assign sigma[15] = q_vector[0] ^ q_vector[8];
  assign sigma[16] = q_vector[0] ^ q_vector[8] ^ q_vector[11];
  assign sigma[17] = q_vector[0] ^ q_vector[8] ^ q_vector[13];
  assign sigma[18] = q_vector[0] ^ q_vector[8] ^ q_vector[17];
  assign sigma[19] = q_vector[0] ^ q_vector[9];
  assign sigma[20] = q_vector[0] ^ q_vector[10];
  assign sigma[21] = q_vector[0] ^ q_vector[10] ^ q_vector[12];
  assign sigma[22] = q_vector[0] ^ q_vector[10] ^ q_vector[16];
  assign sigma[23] = q_vector[0] ^ q_vector[10] ^ q_vector[19];
  assign sigma[24] = q_vector[0] ^ q_vector[11] ^ q_vector[16];
  assign sigma[25] = q_vector[0] ^ q_vector[13];
  assign sigma[26] = q_vector[0] ^ q_vector[13] ^ q_vector[14];
  assign sigma[27] = q_vector[0] ^ q_vector[14];
  assign sigma[28] = q_vector[0] ^ q_vector[16];
  assign sigma[29] = q_vector[0] ^ q_vector[17];
  assign sigma[30] = q_vector[1];
  assign sigma[31] = q_vector[1] ^ q_vector[5] ^ q_vector[6];
  assign sigma[32] = q_vector[1] ^ q_vector[5] ^ q_vector[9];
  assign sigma[33] = q_vector[1] ^ q_vector[6];
  assign sigma[34] = q_vector[1] ^ q_vector[8];
  assign sigma[35] = q_vector[1] ^ q_vector[8] ^ q_vector[19];
  assign sigma[36] = q_vector[1] ^ q_vector[9];
  assign sigma[37] = q_vector[1] ^ q_vector[10];
  assign sigma[38] = q_vector[1] ^ q_vector[10] ^ q_vector[12];
  assign sigma[39] = q_vector[1] ^ q_vector[12] ^ q_vector[18];
  assign sigma[40] = q_vector[1] ^ q_vector[13] ^ q_vector[16];
  assign sigma[41] = q_vector[1] ^ q_vector[15];
  assign sigma[42] = q_vector[1] ^ q_vector[15] ^ q_vector[19];
  assign sigma[43] = q_vector[1] ^ q_vector[16];
  assign sigma[44] = q_vector[2];
  assign sigma[45] = q_vector[2] ^ q_vector[5];
  assign sigma[46] = q_vector[2] ^ q_vector[5] ^ q_vector[6];
  assign sigma[47] = q_vector[2] ^ q_vector[5] ^ q_vector[12];
  assign sigma[48] = q_vector[2] ^ q_vector[6];
  assign sigma[49] = q_vector[2] ^ q_vector[6] ^ q_vector[13];
  assign sigma[50] = q_vector[2] ^ q_vector[6] ^ q_vector[15];
  assign sigma[51] = q_vector[2] ^ q_vector[6] ^ q_vector[18];
  assign sigma[52] = q_vector[2] ^ q_vector[7];
  assign sigma[53] = q_vector[2] ^ q_vector[7] ^ q_vector[8];
  assign sigma[54] = q_vector[2] ^ q_vector[8];
  assign sigma[55] = q_vector[2] ^ q_vector[11];
  assign sigma[56] = q_vector[2] ^ q_vector[11] ^ q_vector[12];
  assign sigma[57] = q_vector[2] ^ q_vector[11] ^ q_vector[18];
  assign sigma[58] = q_vector[2] ^ q_vector[13];
  assign sigma[59] = q_vector[2] ^ q_vector[15];
  assign sigma[60] = q_vector[2] ^ q_vector[15] ^ q_vector[16];
  assign sigma[61] = q_vector[2] ^ q_vector[16];
  assign sigma[62] = q_vector[3];
  assign sigma[63] = q_vector[3] ^ q_vector[5];
  assign sigma[64] = q_vector[3] ^ q_vector[5] ^ q_vector[11];
  assign sigma[65] = q_vector[3] ^ q_vector[6];
  assign sigma[66] = q_vector[3] ^ q_vector[6] ^ q_vector[16];
  assign sigma[67] = q_vector[3] ^ q_vector[7];
  assign sigma[68] = q_vector[3] ^ q_vector[7] ^ q_vector[9];
  assign sigma[69] = q_vector[3] ^ q_vector[7] ^ q_vector[18];
  assign sigma[70] = q_vector[3] ^ q_vector[9] ^ q_vector[10];
  assign sigma[71] = q_vector[3] ^ q_vector[10];
  assign sigma[72] = q_vector[3] ^ q_vector[10] ^ q_vector[11];
  assign sigma[73] = q_vector[3] ^ q_vector[16];
  assign sigma[74] = q_vector[3] ^ q_vector[17];
  assign sigma[75] = q_vector[3] ^ q_vector[17] ^ q_vector[18];
  assign sigma[76] = q_vector[3] ^ q_vector[18];
  assign sigma[77] = q_vector[4];
  assign sigma[78] = q_vector[4] ^ q_vector[5];
  assign sigma[79] = q_vector[4] ^ q_vector[5] ^ q_vector[12];
  assign sigma[80] = q_vector[4] ^ q_vector[6] ^ q_vector[11];
  assign sigma[81] = q_vector[4] ^ q_vector[6] ^ q_vector[16];
  assign sigma[82] = q_vector[4] ^ q_vector[7];
  assign sigma[83] = q_vector[4] ^ q_vector[7] ^ q_vector[15];
  assign sigma[84] = q_vector[4] ^ q_vector[8];
  assign sigma[85] = q_vector[4] ^ q_vector[8] ^ q_vector[17];
  assign sigma[86] = q_vector[4] ^ q_vector[9] ^ q_vector[15];
  assign sigma[87] = q_vector[4] ^ q_vector[9] ^ q_vector[19];
  assign sigma[88] = q_vector[4] ^ q_vector[11];
  assign sigma[89] = q_vector[4] ^ q_vector[12] ^ q_vector[19];
  assign sigma[90] = q_vector[4] ^ q_vector[13];
  assign sigma[91] = q_vector[4] ^ q_vector[15];
  assign sigma[92] = q_vector[4] ^ q_vector[16];
  assign sigma[93] = q_vector[4] ^ q_vector[17];
  assign sigma[94] = q_vector[4] ^ q_vector[17] ^ q_vector[18];
  assign sigma[95] = q_vector[4] ^ q_vector[18] ^ q_vector[19];
  assign sigma[96] = q_vector[4] ^ q_vector[19];
  assign sigma[97] = q_vector[5];
  assign sigma[98] = q_vector[5] ^ q_vector[6];
  assign sigma[99] = q_vector[5] ^ q_vector[7];
  assign sigma[100] = q_vector[5] ^ q_vector[7] ^ q_vector[15];
  assign sigma[101] = q_vector[5] ^ q_vector[9];
  assign sigma[102] = q_vector[5] ^ q_vector[11];
  assign sigma[103] = q_vector[5] ^ q_vector[11] ^ q_vector[14];
  assign sigma[104] = q_vector[5] ^ q_vector[11] ^ q_vector[16];
  assign sigma[105] = q_vector[5] ^ q_vector[12];
  assign sigma[106] = q_vector[5] ^ q_vector[12] ^ q_vector[18];
  assign sigma[107] = q_vector[5] ^ q_vector[12] ^ q_vector[19];
  assign sigma[108] = q_vector[5] ^ q_vector[14];
  assign sigma[109] = q_vector[5] ^ q_vector[15];
  assign sigma[110] = q_vector[5] ^ q_vector[16];
  assign sigma[111] = q_vector[5] ^ q_vector[18];
  assign sigma[112] = q_vector[5] ^ q_vector[19];
  assign sigma[113] = q_vector[6];
  assign sigma[114] = q_vector[6] ^ q_vector[7] ^ q_vector[17];
  assign sigma[115] = q_vector[6] ^ q_vector[7] ^ q_vector[18];
  assign sigma[116] = q_vector[6] ^ q_vector[8] ^ q_vector[12];
  assign sigma[117] = q_vector[6] ^ q_vector[8] ^ q_vector[18];
  assign sigma[118] = q_vector[6] ^ q_vector[9];
  assign sigma[119] = q_vector[6] ^ q_vector[9] ^ q_vector[19];
  assign sigma[120] = q_vector[6] ^ q_vector[11];
  assign sigma[121] = q_vector[6] ^ q_vector[12];
  assign sigma[122] = q_vector[6] ^ q_vector[13];
  assign sigma[123] = q_vector[6] ^ q_vector[13] ^ q_vector[15];
  assign sigma[124] = q_vector[6] ^ q_vector[15];
  assign sigma[125] = q_vector[6] ^ q_vector[15] ^ q_vector[16];
  assign sigma[126] = q_vector[6] ^ q_vector[17];
  assign sigma[127] = q_vector[6] ^ q_vector[17] ^ q_vector[18];
  assign sigma[128] = q_vector[7];
  assign sigma[129] = q_vector[7] ^ q_vector[8];
  assign sigma[130] = q_vector[7] ^ q_vector[9];
  assign sigma[131] = q_vector[7] ^ q_vector[9] ^ q_vector[17];
  assign sigma[132] = q_vector[7] ^ q_vector[10];
  assign sigma[133] = q_vector[7] ^ q_vector[10] ^ q_vector[17];
  assign sigma[134] = q_vector[7] ^ q_vector[11];
  assign sigma[135] = q_vector[7] ^ q_vector[11] ^ q_vector[17];
  assign sigma[136] = q_vector[7] ^ q_vector[15];
  assign sigma[137] = q_vector[7] ^ q_vector[15] ^ q_vector[19];
  assign sigma[138] = q_vector[7] ^ q_vector[17];
  assign sigma[139] = q_vector[7] ^ q_vector[18];
  assign sigma[140] = q_vector[7] ^ q_vector[19];
  assign sigma[141] = q_vector[8];
  assign sigma[142] = q_vector[8] ^ q_vector[10];
  assign sigma[143] = q_vector[8] ^ q_vector[10] ^ q_vector[17];
  assign sigma[144] = q_vector[8] ^ q_vector[11] ^ q_vector[16];
  assign sigma[145] = q_vector[8] ^ q_vector[12] ^ q_vector[19];
  assign sigma[146] = q_vector[8] ^ q_vector[13] ^ q_vector[15];
  assign sigma[147] = q_vector[8] ^ q_vector[15];
  assign sigma[148] = q_vector[8] ^ q_vector[15] ^ q_vector[18];
  assign sigma[149] = q_vector[8] ^ q_vector[16] ^ q_vector[18];
  assign sigma[150] = q_vector[8] ^ q_vector[17];
  assign sigma[151] = q_vector[8] ^ q_vector[18];
  assign sigma[152] = q_vector[8] ^ q_vector[19];
  assign sigma[153] = q_vector[9];
  assign sigma[154] = q_vector[9] ^ q_vector[10] ^ q_vector[11];
  assign sigma[155] = q_vector[9] ^ q_vector[11];
  assign sigma[156] = q_vector[9] ^ q_vector[12];
  assign sigma[157] = q_vector[9] ^ q_vector[12] ^ q_vector[14];
  assign sigma[158] = q_vector[9] ^ q_vector[12] ^ q_vector[16];
  assign sigma[159] = q_vector[9] ^ q_vector[14] ^ q_vector[18];
  assign sigma[160] = q_vector[9] ^ q_vector[15];
  assign sigma[161] = q_vector[9] ^ q_vector[16];
  assign sigma[162] = q_vector[9] ^ q_vector[17];
  assign sigma[163] = q_vector[9] ^ q_vector[18];
  assign sigma[164] = q_vector[10];
  assign sigma[165] = q_vector[10] ^ q_vector[12];
  assign sigma[166] = q_vector[10] ^ q_vector[12] ^ q_vector[13];
  assign sigma[167] = q_vector[10] ^ q_vector[12] ^ q_vector[15];
  assign sigma[168] = q_vector[10] ^ q_vector[13] ^ q_vector[17];
  assign sigma[169] = q_vector[10] ^ q_vector[15];
  assign sigma[170] = q_vector[10] ^ q_vector[16];
  assign sigma[171] = q_vector[10] ^ q_vector[17];
  assign sigma[172] = q_vector[10] ^ q_vector[18];
  assign sigma[173] = q_vector[10] ^ q_vector[18] ^ q_vector[19];
  assign sigma[174] = q_vector[11];
  assign sigma[175] = q_vector[11] ^ q_vector[12];
  assign sigma[176] = q_vector[11] ^ q_vector[14];
  assign sigma[177] = q_vector[11] ^ q_vector[16];
  assign sigma[178] = q_vector[11] ^ q_vector[17];
  assign sigma[179] = q_vector[11] ^ q_vector[18];
  assign sigma[180] = q_vector[12];
  assign sigma[181] = q_vector[12] ^ q_vector[13];
  assign sigma[182] = q_vector[12] ^ q_vector[13] ^ q_vector[16];
  assign sigma[183] = q_vector[12] ^ q_vector[14];
  assign sigma[184] = q_vector[12] ^ q_vector[15];
  assign sigma[185] = q_vector[12] ^ q_vector[15] ^ q_vector[17];
  assign sigma[186] = q_vector[12] ^ q_vector[17];
  assign sigma[187] = q_vector[12] ^ q_vector[19];
  assign sigma[188] = q_vector[13];
  assign sigma[189] = q_vector[13] ^ q_vector[14];
  assign sigma[190] = q_vector[13] ^ q_vector[15];
  assign sigma[191] = q_vector[13] ^ q_vector[16];
  assign sigma[192] = q_vector[13] ^ q_vector[16] ^ q_vector[17];
  assign sigma[193] = q_vector[13] ^ q_vector[17];
  assign sigma[194] = q_vector[14] ^ q_vector[18];
  assign sigma[195] = q_vector[15];
  assign sigma[196] = q_vector[15] ^ q_vector[16];
  assign sigma[197] = q_vector[15] ^ q_vector[17] ^ q_vector[18];
  assign sigma[198] = q_vector[15] ^ q_vector[18];
  assign sigma[199] = q_vector[15] ^ q_vector[18] ^ q_vector[19];
  assign sigma[200] = q_vector[15] ^ q_vector[19];
  assign sigma[201] = q_vector[16];
  assign sigma[202] = q_vector[16] ^ q_vector[17];
  assign sigma[203] = q_vector[16] ^ q_vector[18];
  assign sigma[204] = q_vector[17];
  assign sigma[205] = q_vector[17] ^ q_vector[18];
  assign sigma[206] = q_vector[17] ^ q_vector[18] ^ q_vector[19];
  assign sigma[207] = q_vector[17] ^ q_vector[19];
  assign sigma[208] = q_vector[18];
  assign sigma[209] = q_vector[19];

  always @* begin
    for (i_cls = 0; i_cls < NUM_CLS; i_cls = i_cls + 1) begin
      T_next[i_cls] = (update) ? (sigma[i_cls] ^ T_reg[i_cls])
                              : T_reg[i_cls];
    end
    next_color = (update) ? ((current_color == MAX_COLOR-1) ? 0 : (current_color + 1)) : 0;
  end
endmodule
